### ISSUE TITLE
关于fling运行的一些问题以及如何添加算法的求助！

### ISSUE THREAD

**Issue by Wzifu** [kxzxvbk/Fling#32]
您好，首先非常感谢这个项目，对我的学习很有帮助！ 我在配置环境时候，使用python argzoo/mnist/mnist_fedavg_cnn_toy_config.py没有问题，但是在运行fling run -c argzoo/mnist/mnist_fedper_cnn_toy_config.py -p personalized_model_pipeline会报错，报错如下，我只截取部分：
C:\Users\文文\Documents\BaiduNetdiskWorkspace\成电资料\研究学习\FL_code\Fling>fling run -c flzoo/mnist/mnist_fedper_cnn_toy_config.py -p personalized_model_pipeline
Traceback (most recent call last):
  File "c:\users\文文\appdata\local\programs\python\python38\lib\tokenize.py", line 330, in find_cookie
    line_string = line.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 11: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\文文\AppData\Local\Programs\Python\Python38\Scripts\fling-script.py", line 11, in <module>
  File "c:\users\文文\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)

……
File "c:\users\文文\appdata\local\programs\python\python38\lib\tokenize.py", line 335, in find_cookie
    raise SyntaxError(msg)
SyntaxError: invalid or missing encoding declaration for 'C:\\Users\\文文\\AppData\\Local\\Programs\\Python\\Python38\\Scripts\\fling-script.py'

请问这种情况怎么处理。
还有我看main里面有一个关于如何添加算法的文档，不过内容是空白的，不管中文还是英文。
希望作者可以看一下，再次感谢！

**Comment by kxzxvbk** [comment]
It is an unusual problem. The command "python argzoo/mnist/mnist_fedavg_cnn_toy_config.py" is correctly executed but "fling run -c argzoo/mnist/mnist_fedper_cnn_toy_config.py -p personalized_model_pipeline" is not. This indicates that it is the CLI that goes something wrong.
The easiest way to fix this problem is to avoid using CLI. You can run ``python argzoo/mnist/mnist_fedper_cnn_toy_config.py`` as a substitution. I'm not sure why CLI does not work in your system. Maybe it is because your path is not pure in English (e.g. “/文文/”).  Maybe you can change your path in English.
It doesn't seem to be a bug of Fling. If you have more information about this bug, please feel free to let us know.

**Comment by kxzxvbk** [comment]
For the second problem, we will release new documents in this month later.

**Comment by Wzifu** [comment]
在此感谢！我根据你的帮助，修改了路劲命同时强制使用utf-8，乱码和以上错误已经不在出现了。但是此时我执行代码，会发生一下错误，是什么原因造成的。windows系统下不能直接运行么
C:\APPlication\Fling_Code\Fling>fling run -c flzoo/mnist/mnist_fedper_cnn_toy_config.py -p personalized_model_pipeline
failed to create process.

**Comment by kxzxvbk** [comment]
That's strange. I can run this command in my windows computer. Can you provide a complete error message?

**Comment by Wzifu** [comment]
使用fling命令我还无法去执行，Error message只会显示failed to create process，我需要再去读一下文档进行学习。所以我只是用Python命令执行项目。我对一些项目的data路径做了调成，同时修改了一些data数据的位置，现在大部分的算法已经可以运行了。唯独cifar10_fedcac_resnet_config.py和cifar101_fedcac_resnet_config.py.他们在执行期间，会出现问题。可以客户初始化，可以执行round 0。但是下一步开始，应该是执行和下发的过程中，也就是round 1开始，就会出现如下错误：
Traceback (most recent call last):
  File "C:\APPlication\Fling_Code\Fling\flzoo\cifar100\cifar100_fedcac_resnet_config.py", line 47, in <module>
    personalized_model_pipeline(exp_args, seed=seed)
  File "C:\APPlication\Fling_Code\Fling\fling\pipeline\personalized_model_pipeline.py", line 87, in personalized_model_pipeline
    trans_cost = group.aggregate(i)
  File "C:\APPlication\Fling_Code\Fling\fling\component\group\fedcac_group.py", line 116, in aggregate
    self.sync()
  File "C:\APPlication\Fling_Code\Fling\fling\component\group\fedcac_group.py", line 32, in sync
    tempGlobalModel.load_state_dict(self.server.glob_dict)
File "C:\Users\文文\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ResNet:
	Missing key(s) in state_dict: "bn1.running_mean", "bn1.running_var", "layers.0.0.bn1.running_mean", "layers.0.0.bn1.running_var", "layers.0.0.bn2.running_mean", "layers.0.0.bn2.running_var", …)
	cifar 的数据集位置也没有修改，是直接运行py文件进行训练。是否是我没有输入和调整参数造成的，请问这是什么原因造成的，再次麻烦您了！

**Comment by XinghaoWu** [comment]
Thanks for your feedback! The bug has been fixed in #33 . You can use the latest version of Fling to avoid this problem.
Based on your feedback, we found a bug with the 'get_parameters' function in the 'torch_utils.py' file. It dismisses the 'running_mean' and 'running_var' keys in the BN layers, causing FedCAC to error in initializing personalized models. 
Thanks again for your feedback. You are welcome to ask questions at any time during your use.
